Last Attempt to fix error
Unsuccessful in fixing back end error. Unable to view front end due to error. applicationContext.xml is in the WEB-INF folder but the error says otherwise.

SEVERE: Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from ServletContext resource [/WEB-INF/applicationContext.xml]; nested exception is java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/applicationContext.xml]